[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge"]
name = "rcghpge.github.io"
platforms = ["linux-64"]
version = "0.1.2"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
nodejs = ">=25.6.0,<25.7"
vim = ">=9.1.1858,<10"
texinfo = ">=7.2,<8"
tldr = ">=3.4.4,<4"
trivy = ">=0.65.0,<0.66"
qtsass = ">=0.4.0,<0.5"
nano = ">=8.7,<9"

[pypi-dependencies]
npm = ">=0.1.1, <0.2"
emacs = ">=24.1.50.1.post20120610, <25"
clamd = ">=1.0.2, <2"
