[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge"]
name = "homepage"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
nodejs = ">=25.2.1,<25.3"
vim = ">=9.1.1858,<10"
texinfo = ">=7.2,<8"
tldr = ">=3.4.3,<4"

[pypi-dependencies]
npm = ">=0.1.1, <0.2"
emacs = ">=24.1.50.1.post20120610, <25"
